/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Rent extends javax.swing.JFrame {

    /**
     * Creates new form Rent
     */
    
    
    public Rent() {
        initComponents();
        Dimension windows = Toolkit.getDefaultToolkit().getScreenSize();
        int x = windows.width / 2 - this.getSize().width / 2;
        int y = windows.width / 3 - this.getSize().width / 2;
        this.setLocation(x,y);
        this.setResizable(false);
    }
    
    public class Game {
        protected String name;
        protected int price;

        public Game(String name, int price) {
            this.name = name;
            this.price = price;
        }

        @Override
        public String toString() {
            return name; 
        }
    }

    class BaldurGateIII extends Game {
        public BaldurGateIII() {
            super("Baldur Gate III", 20000);
        }
    }

    class Fifa23 extends Game {
        public Fifa23() {
            super("Fifa 23", 5000);
        }
    }

    class Spiderman2 extends Game {
        public Spiderman2() {
            super("Spiderman 2", 20000);
        }
    }

    class Cyberpunk extends Game {
        public Cyberpunk() {
            super("Cyberpunk", 20000);
        }
    }

    class GodOfWar extends Game {
        public GodOfWar() {
            super("God of War", 25000);
        }
    }

    class NBA2K24 extends Game {
        public NBA2K24() {
            super("NBA2K24", 5000);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        gameoption = new javax.swing.JList<>();
        name = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chooselabel = new javax.swing.JLabel();
        Quantitybox = new javax.swing.JComboBox<>();
        quantitylabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Resetbutton = new javax.swing.JButton();
        quantitylabel1 = new javax.swing.JLabel();
        Durationbox = new javax.swing.JComboBox<>();
        Rent = new javax.swing.JButton();
        Paybutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Closebutton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        container.setBackground(new java.awt.Color(209, 214, 216));
        container.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        container.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 141, 369, 179));

        gameoption.setFont(new java.awt.Font("Segoe UI Semibold", 1, 28)); // NOI18N
        gameoption.setModel(new javax.swing.AbstractListModel<Game>() {
            Game[] games = {new BaldurGateIII(), new Fifa23(), new Spiderman2(), new Cyberpunk(), new GodOfWar(), new NBA2K24()};

            public int getSize() {
                return games.length;
            }

            public Game getElementAt(int i) {
                return games[i];
            }
        });
        jScrollPane2.setViewportView(gameoption);

        container.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 200, 250));
        container.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 163, 249, 31));

        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        container.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 259, 249, 31));

        jLabel1.setText("Please Enter Your Identity");
        container.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 62, 203, -1));

        jLabel2.setText("Name:");
        container.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 141, -1, -1));

        jLabel3.setText("Email");
        container.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 231, -1, -1));

        chooselabel.setText("Plese Choose Yourgame");
        container.add(chooselabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 62, -1, -1));

        Quantitybox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        container.add(Quantitybox, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 387, -1, -1));

        quantitylabel.setText("Quantity");
        container.add(quantitylabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 387, -1, -1));

        jLabel7.setText("Receipt");
        container.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 62, 203, -1));

        Resetbutton.setText("Reset");
        Resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetbuttonActionPerformed(evt);
            }
        });
        container.add(Resetbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 352, 83, -1));

        quantitylabel1.setText("Duration (days)");
        container.add(quantitylabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 419, -1, -1));

        Durationbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "4", "5", "6", "7", "8", "9", "10" }));
        container.add(Durationbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 416, -1, -1));

        Rent.setText("Rent");
        Rent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentActionPerformed(evt);
            }
        });
        container.add(Rent, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 352, 83, -1));

        Paybutton.setText("Pay");
        Paybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaybuttonActionPerformed(evt);
            }
        });
        container.add(Paybutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 352, 228, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("WELCOME TO BANANA SHOP");
        container.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        jLabel5.setText("-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        container.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 913, -1));

        Closebutton.setText("Close");
        Closebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClosebuttonActionPerformed(evt);
            }
        });
        container.add(Closebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, -1, -1));

        getContentPane().add(container, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 940, 490));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo/mainmenu.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public int calculateTotalPrice(Game selectedGame, int quantity, int duration) {
       int basePrice;
        basePrice = selectedGame.price;

    // Calculate total price based on the selected game
    return basePrice * quantity * duration;
    }
    
    //overloading
    private int calculateTotalPrice(Game selectedGame, int quantity, int duration, double taxPercentage ) {
        int basePrice = calculateTotalPrice(selectedGame, quantity, duration);

        
        double tax = taxPercentage  / 100.0;
        double totalPriceWithTax = basePrice + (basePrice * tax);

        return (int) totalPriceWithTax;
}
    
    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed
    
    private void ResetbuttonActionPerformed(java.awt.event.ActionEvent evt) {                                         
    // Reset the text area
    jTextArea1.setText("");
    name.setText("");
    Email.setText("");
    gameoption.clearSelection();
    Quantitybox.setSelectedIndex(0);
    Durationbox.setSelectedIndex(0);
} 
    private void RentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentActionPerformed
        
    Game selectedGame = gameoption.getSelectedValue();
    int quantity = Integer.parseInt(Quantitybox.getSelectedItem().toString());
    int duration = Integer.parseInt(Durationbox.getSelectedItem().toString());

    String enteredName = name.getText();
    String enteredEmail = Email.getText();

    //validade user input
    if (selectedGame == null || enteredName.isEmpty() || enteredEmail.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter your name, email, and select a game before renting.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // price
    double taxPercentage = 5.0;
    int totalPriceWithoutTax = calculateTotalPrice(selectedGame, quantity, duration);
    int totalPriceWithTax = calculateTotalPrice(selectedGame, quantity, duration, taxPercentage);

    //current date
    java.util.Date currentDate = new java.util.Date();
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");

    //expected return date
    Calendar cal = Calendar.getInstance();
    cal.setTime(currentDate);
    cal.add(Calendar.DAY_OF_MONTH, duration);
    String expectedReturnDate = sdf.format(cal.getTime());

    
    jTextArea1.setText("Name\t\t: " + enteredName + "\n");
    jTextArea1.append("Email\t\t: " + enteredEmail + "\n");
    jTextArea1.append("Price without Tax\t: " + totalPriceWithoutTax + "\n");
    jTextArea1.append("Price with Tax\t\t: " + totalPriceWithTax + "\n");
    jTextArea1.append("Tax\t\t: " + taxPercentage + "%\n");
    jTextArea1.append("Expected Return\t: " + expectedReturnDate);
    }//GEN-LAST:event_RentActionPerformed

    @Override
    protected void processWindowEvent(WindowEvent e) {
        if (e.getID() == WindowEvent.WINDOW_CLOSING) {
            // Handle window closing event here
            int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirm Exit", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                System.exit(0);
            }
        }
        super.processWindowEvent(e);
    }
    private void ClosebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClosebuttonActionPerformed
       int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirm Exit", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_ClosebuttonActionPerformed

    private void PaybuttonActionPerformed(java.awt.event.ActionEvent evt) {                                       
    
    int dialogResult = JOptionPane.showConfirmDialog(this, "Thank you for your purchase!\nDo you want to exit the program?", "Purchase Confirmation", JOptionPane.OK_CANCEL_OPTION);

    // Check user's choice
    if (dialogResult == JOptionPane.OK_OPTION) {
       
        System.exit(0);
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Closebutton;
    private javax.swing.JComboBox<String> Durationbox;
    private javax.swing.JTextField Email;
    private javax.swing.JButton Paybutton;
    private javax.swing.JComboBox<String> Quantitybox;
    private javax.swing.JButton Rent;
    private javax.swing.JButton Resetbutton;
    private javax.swing.JLabel background;
    private javax.swing.JLabel chooselabel;
    private javax.swing.JPanel container;
    private javax.swing.JList<Game> gameoption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField name;
    private javax.swing.JLabel quantitylabel;
    private javax.swing.JLabel quantitylabel1;
    // End of variables declaration//GEN-END:variables
}
